# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 426d78efaff249753fbc8840acfb403d5ea7db395263e42224ae91f6ca23347fd9a722e754e2b1bc708b91d5a91f455e9fb2896086047f93a20da452d9540f5f

test:
  secret_key_base: 8bb30176f35bfb08552e71bab49ab526dab5014ffb268b3430ec9dd6c1b53b994d97df10941a1b2b95ba4304a5010b42a95a41b1994cd42a34a662b5b15e55ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
